project:
  type: website

execute:
  freeze: auto

website:
  title: "SSEEN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: members.qmd
        text: Members
      - href: events.qmd
        text: Events
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



