project:
  type: website

execute:
  freeze: auto

website:
  title: "SSEEN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: aims.qmd
        text: Aims
      - href: partners.qmd
        text: Partners
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



