---
title: "Members and partners"
---

## Network Member institutions

### University of Edinburgh

- Statistics group, Data \& Decisions, School of Mathematics, The University of Edinburgh (contact: [Finn Lindgren](mailto::Finn.Lindgren@ed.ac.uk))

### University of Glasgow

The Statistics and Data analytics group at Glasgow has longstanding expertise in the development and application of Statistical and Data Analytics methodology in both Ecology and Environmental Sciences. About 20 members of permanent staff are undertaking research focussing directly on a large variety of different environmental and ecological applications, including the modelling of biodiversity, species distributions modelling, species conservation, air and water quality monitoring, pollution modelling and the effect of pollution on disease risk, wind speed modelling, land slide prediction and many more. The group also has a strong track-record of working with spatial- and spatio-temporal data, and combining data from different sources through data and model fusion. This includes, for instance, data collected through sensor networks, satellites and citizen science initiatives.

Contact: [??? ???](mailto:???)

### University of St Andrews

- ?, University of St Andrews

### BioSS

[Biomathematics and Statistics Scotland (BioSS)](www.bioss.ac.uk)
specialises in the development
and application of the quantitative methods needed to enhance scientific
knowledge and impact. BioSS is unique within the UK research community thanks
to a focus on method development combined with applied quantitative research and
impact, based on active collaboration with quantitative specialists and with
natural and social scientists.

BioSS is one of the Scottish Environment, Food
and Agriculture Research Institutes (SEFARI), and formally a part of the James
Hutton Institute. BioSS has over 40 scientific colleagues with different
quantitative specialities and a range of application areas, including
environmental science and ecology, with particular strengths in modelling
the ecological impacts of offshore renewables, spatial and temporal modelling,
impact and mitigation of climate change, species distribution modelling,
biodiversity assessment and monitoring, pollution modelling and in soil and
peatland health.

Contacts: [Ken Newman](mailto::Ken.Newman@bioss.ac.uk);
[Mark Brewer](mailto::Mark.Brewer@bioss.ac.uk)

## Network partners

 - ...
 - ...
